### ISSUE TITLE
User Story 10: Refactoring

### ISSUE THREAD

**Issue by AnnaD91** [e-rmkt/capstone-project-travel-app#26]
## Value proposition

`As a` web developer
`I want to` have clean and semantic code
`so that`  my code has more structure, is readable, efficient and understandable. 

### Schema
   - [ ] There will be a new Schema, where we change the type from Array-Object-Array to 
           an Array of Objects
   - [ ] There will be no more destructuring of the data, because of the new schema
   - [ ] There will be an time stamp for the update- and the create-date
### Buttons
   - [ ] There will be one ActionButton instead of the CreateButton and the DeleteButton
### Component Structure
   - [ ]  There will be a folder-file-tree, that explains which components will be found in 
            which folder, e.g. components/Buttons/ActionButton/...
### Routing
   - [ ] The user will be redirected to the details page, after clicking cancel in the edit form
### Input fields
   - [ ] There will be an dropdown for countries and cities, where we will have only cities 
           that fits to the country
### Fetcher
- [ ] The fetcher will be on the _app.js and the data will be forwarded to all components
### Design
   - [ ] The trips will be sorted, so that the trip with the closest start date will be on the first 
           place and the rest of the list will be in descending order
   - [ ]  The trips will be categorized (ongoing trip, future trip/trips, past trip/trips)
   - [ ]  The trips of the past will be greyed out

      

### Schema
- [ ] Change the schema and delete the array out of the objects, so that there will be an object inside of an object
- [ ] add the timestamp to the schema `{ timestamps: true }`
- [ ] delete the destructuring and the maps (Location and TimePeriod component as well) and replace it with {...trips}

### Buttons
- [ ] Create an `ActionButton` Component and change the component calls of the `CreateButton` and `DeleteButton` to `ActionButton`

### Component Structure
- [ ] Create a folder structure, that fits your components, and move the component folders into the new folders and update the import as well, if necessary

### Routing
- [ ] Change the `href` in the Link Component for the `cancelButton` to the details page, if its clicked on the edit form

### Input fields
- [ ] Change the input type of country and city to select and use the library country-city-state for the options like in this prototype [CodeSandbox](https://codesandbox.io/s/country-city-select-2y4pg7)
### Fetcher
   - [ ] Move the fetcher to the _app.js and give the {...trips} as property to all 
pages/components 
### Design
- [ ] Use the sort method on the array and sort the trips in descending order with the closest start date on the first place
- [ ] Create categories for the trips (Ongoing trip, future trip/trips, past trip/trips)
- [ ] Create a design for the past trips (greyed out)

```

**Comment by miriam-ertl** [comment]
★ ★ ★ ★ ★ Very well done, excellent quality to read and understand.
